version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: chmod +x gradlew
      - run: ./gradlew clean build

workflows:
  version: 2
  build:
    jobs:
      - build
