apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui-deployment
  namespace: app-infra
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "healthsystem-kafka-kafka-0"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: healthsystem-kafka-kafka-bootstrap:9092 # <- service-name.namespace:9092
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  namespace: app-infra
spec:
  type: NodePort
  selector:
    app: kafka-ui
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
