springdoc:
  swagger-ui:
    disable-swagger-default-url: true

server:
  port: 8031

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:31355
      group-id: doctor_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: org.smf.healthsystem.doctorservice.modal
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: localhost:31355
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    mongodb:
      uri: mongodb://localhost:27017/medrec
  # producer
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#  spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#  spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonDeserializer

DOCTOR_TOPIC: doctor